services:
  iut_service:
    container_name: iut_service
    image: node:lts
    env_file: ./services/.env
    working_dir: /usr/src/app
    volumes:
      - ./services/api:/usr/src/app
    ports:
      - 3333:3000
    command: npm run watch 
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut

  iut_adminer:
    container_name: iut_adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - iut_db
    networks:
      - iut
  
  iut_db:
    container_name: iut_db
    image: mariadb:latest
    env_file: ./services/.env
    volumes:
      - ./services/db:/var/lib/mysql
      - ./services/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./services/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - iut

networks:
  iut:
    driver: bridge